version: '3.8'
services:
    api-gateway:
        build:
            context: ./applications/api-gateway
            dockerfile: Dockerfile
        ports:
            - 3000:3000
        networks:
            - life-helper-app

networks:
    life-helper-app:
        driver: bridge